name: validations

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Upgrade Python packaging tools
      run: pip install --disable-pip-version-check --upgrade pip setuptools wheel

    - name: Install ddev
      run: pip install "datadog-checks-dev[cli]"

    - name: Configure ddev
      run: |
        ddev config set repos.extras .
        ddev config set repo extras

    - name: Run configuration validation
      run: |
        ddev validate config

    - name: Run HTTP wrapper validation
      run: |
        ddev validate http

    - name: Run legacy signature validation
      run: |
        ddev validate legacy-signature